version: '3.9'
services:
  backend:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/needymeds-backend:latest
    container_name: needymeds-backend
    ports:
      - '9000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
